# Generated by Django 5.0.1 on 2024-01-10 10:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id пользователя')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email адрес')),
                ('nickname', models.CharField(verbose_name='Никнейм')),
                ('sex', models.CharField(choices=[('M', 'Man'), ('W', 'Woman')], verbose_name='Пол')),
                ('birthdate', models.DateTimeField(verbose_name='Возраст')),
                ('occupation', models.CharField(choices=[('RS', 'Remote student'), ('NRS', 'Not remote student'), ('RW', 'Remote worker'), ('NRW', 'Not remote worker'), ('OAR', 'On a rest')], verbose_name='Занятость')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата регистрации')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
