# Generated by Django 5.0.1 on 2024-01-10 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birthdate',
            field=models.DateTimeField(verbose_name='Дата рождения'),
        ),
    ]
