# Generated by Django 5.0.1 on 2024-01-10 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_is_active_customuser_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birthdate',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_id',
            field=models.BigAutoField(primary_key=True, serialize=False, unique=True, verbose_name='Id пользователя'),
        ),
    ]
