# Generated by Django 5.0.1 on 2024-05-11 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeexplorer_app', '0007_alter_establishments_picture'),
        ('users', '0004_alter_customuser_sex_alter_posts_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='favourites',
            field=models.ManyToManyField(blank=True, null=True, to='coffeeexplorer_app.establishments', verbose_name='Избранное'),
        ),
    ]
