# Generated by Django 5.0.1 on 2024-05-13 16:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_favourites'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='alt_brewing',
            field=models.BooleanField(blank=True, null=True, verbose_name='Нужны ли альтернативные способы заваривания?'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='alt_milk',
            field=models.BooleanField(blank=True, null=True, verbose_name='Нужно ли альтернативное молоко'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='big_pets',
            field=models.BooleanField(blank=True, null=True, verbose_name='Важна ли возможность посетить с большой собакой'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='decaf',
            field=models.BooleanField(blank=True, null=True, verbose_name='Нужен ли декаф'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='food',
            field=models.BooleanField(blank=True, null=True, verbose_name='Нужна ли кухня'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='non_coffee_drink',
            field=models.BooleanField(blank=True, null=True, verbose_name='Нужы ли не кофейные напитки'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='place_for_work',
            field=models.BooleanField(blank=True, null=True, verbose_name='Нужны ли места для работы'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='recommendations',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None, verbose_name='Рекомендации заведений'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='small_pets',
            field=models.BooleanField(blank=True, null=True, verbose_name='Важна ли возможность посетить с маленькой собакой'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='veg_positions',
            field=models.BooleanField(blank=True, null=True, verbose_name='Нужны ли вегетарианские позиции?'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='wifi',
            field=models.BooleanField(blank=True, null=True, verbose_name='Нужен ли wifi'),
        ),
    ]
