# Generated by Django 5.0.1 on 2024-05-13 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_alt_brewing_customuser_alt_milk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avg_bill',
            field=models.FloatField(default=500, verbose_name='Допустимый средний чек'),
            preserve_default=False,
        ),
    ]
