# Generated by Django 5.0.1 on 2024-05-24 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customuser_avg_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='specialty_coffee',
            field=models.BooleanField(blank=True, null=True, verbose_name='Нужен ли specialty кофе'),
        ),
    ]
