# Generated by Django 5.0.1 on 2024-05-25 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customuser_specialty_coffee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avg_bill',
            field=models.FloatField(blank=True, null=True, verbose_name='Допустимый средний чек'),
        ),
    ]
