services:
  django:
    build: ./
    container_name: djangoapp
    restart: always
    ports:
      - 8000:8000
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    networks:
      - myNetwork
    volumes:
      - ./:/usr/src/app/
      - django_static_volume:/usr/src/app/static
      - django_media_volume:/usr/src/app/media
    depends_on:
      - postgres
    env_file:
      - ./djangoProject/.env
  node:
    build: ./reactapp
    container_name: reactapp
    restart: always
    ports:
      - 3000:3000
    command: npm start
    depends_on:
      - django
    networks:
      - myNetwork
    volumes:
      - ./reactapp/public/:/usr/src/app/public/
      - ./reactapp/src/:/usr/src/app/src/
    env_file:
      - ./reactapp/.env
    stdin_open: true
  
  postgres:
    image: postgres:16.1-alpine
    container_name: postgresdb
    ports:
      - 5435:5435
    networks:
      - myNetwork
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    env_file:
      - ./djangoProject/.env

volumes:
  postgres_volume:
  django_static_volume:
  django_media_volume:

networks:
  myNetwork:
    driver: bridge