# Generated by Django 5.0.1 on 2024-01-11 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('cityID', models.AutoField(primary_key=True, serialize=False, verbose_name='ID города')),
                ('name', models.CharField(max_length=50, verbose_name='Название города')),
            ],
        ),
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('whID', models.AutoField(primary_key=True, serialize=False, verbose_name='ID графика')),
                ('day_of_week', models.CharField(max_length=10, verbose_name='День недели')),
                ('time_from', models.TimeField(verbose_name='Время открытия')),
                ('time_to', models.TimeField(verbose_name='Время закрытия')),
            ],
        ),
        migrations.CreateModel(
            name='MetroStations',
            fields=[
                ('msID', models.AutoField(primary_key=True, serialize=False, verbose_name='ID станции метро')),
                ('name', models.CharField(max_length=50, verbose_name='Название станции метро')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffeeexplorer_app.cities', verbose_name='Город')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('addressID', models.AutoField(primary_key=True, serialize=False, verbose_name='ID адреса')),
                ('street', models.CharField(max_length=100, verbose_name='Улица')),
                ('building', models.CharField(max_length=10, verbose_name='Номер дома')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffeeexplorer_app.cities', verbose_name='Город')),
                ('metro_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffeeexplorer_app.metrostations', verbose_name='Станция метро')),
            ],
        ),
        migrations.CreateModel(
            name='Establishments',
            fields=[
                ('establishmentID', models.AutoField(primary_key=True, serialize=False, verbose_name='ID заведения')),
                ('name', models.CharField(max_length=100, verbose_name='Название заведения')),
                ('description', models.TextField(max_length=200, verbose_name='Описание')),
                ('picture', models.URLField(verbose_name='Изображение')),
                ('avg_bill', models.FloatField(verbose_name='Средний чек')),
                ('veg_positions', models.BooleanField(verbose_name='Наличие вегетарианских позиций')),
                ('alt_brewing', models.BooleanField(verbose_name='Наличие альтернативных способов заваривания')),
                ('alt_milk', models.BooleanField(verbose_name='Наличие альтернативного молока')),
                ('pets', models.BooleanField(verbose_name='Наличие возможности посетить с питомцем')),
                ('food', models.BooleanField(verbose_name='Наличие кухни')),
                ('non_coffee_drink', models.BooleanField(verbose_name='Наличие не кофейных напитков')),
                ('decaf', models.BooleanField(verbose_name='Наличие декафа')),
                ('wifi', models.BooleanField(verbose_name='Наличие wifi')),
                ('place_for_work', models.BooleanField(verbose_name='Наличие мест для работы')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffeeexplorer_app.address', verbose_name='Адрес')),
                ('working_hours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffeeexplorer_app.workinghours', verbose_name='График работы')),
            ],
        ),
    ]
