# Generated by Django 5.0.1 on 2024-01-12 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeexplorer_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Адрес', 'verbose_name_plural': 'Адреса'},
        ),
        migrations.AlterModelOptions(
            name='cities',
            options={'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
        migrations.AlterModelOptions(
            name='establishments',
            options={'verbose_name': 'Заведение', 'verbose_name_plural': 'Заведения'},
        ),
        migrations.AlterModelOptions(
            name='metrostations',
            options={'verbose_name': 'Станция метро', 'verbose_name_plural': 'Станции метро'},
        ),
        migrations.AlterModelOptions(
            name='workinghours',
            options={'verbose_name': 'График работы', 'verbose_name_plural': 'Графики работы'},
        ),
        migrations.RemoveField(
            model_name='establishments',
            name='working_hours',
        ),
        migrations.AddField(
            model_name='workinghours',
            name='establishment',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='coffeeexplorer_app.establishments', verbose_name='Заведение'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='metro_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coffeeexplorer_app.metrostations', verbose_name='Станция метро'),
        ),
        migrations.AlterField(
            model_name='establishments',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coffeeexplorer_app.address', verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='metrostations',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coffeeexplorer_app.cities', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='day_of_week',
            field=models.CharField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], verbose_name='День недели'),
        ),
    ]
