# Generated by Django 5.0.1 on 2024-01-12 16:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeexplorer_app', '0002_alter_address_options_alter_cities_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workinghours',
            name='day_of_week',
        ),
        migrations.RemoveField(
            model_name='workinghours',
            name='time_from',
        ),
        migrations.RemoveField(
            model_name='workinghours',
            name='time_to',
        ),
        migrations.AddField(
            model_name='workinghours',
            name='friday_from',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Пятница открытие'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workinghours',
            name='friday_to',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Пятница закрытие'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workinghours',
            name='monday_from',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Понедельник открытие'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workinghours',
            name='monday_to',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Понедельник закрытие'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workinghours',
            name='saturday_from',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Суббота открытие'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workinghours',
            name='saturday_to',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Суббота закрытие'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workinghours',
            name='sunday_from',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Воскресенье открытие'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workinghours',
            name='sunday_to',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Воскресенье закрытие'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workinghours',
            name='thursday_from',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Четверг открытие'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workinghours',
            name='thursday_to',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Четверг закрытие'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workinghours',
            name='tuesday_from',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Вторник открытие'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workinghours',
            name='tuesday_to',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Вторник закрытие'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workinghours',
            name='wednesday_from',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Среда открытие'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workinghours',
            name='wednesday_to',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Среда закрытие'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='establishments',
            name='picture',
            field=models.ImageField(upload_to='uploads/establishments', verbose_name='Изображение'),
        ),
    ]
