# Generated by Django 5.0.1 on 2024-01-17 12:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeexplorer_app', '0003_remove_workinghours_day_of_week_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishments',
            name='close',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=(0, 1), size=None, verbose_name='Похожие заведения'),
            preserve_default=False,
        ),
    ]
