# Generated by Django 5.0.1 on 2024-04-30 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeexplorer_app', '0006_alter_establishments_close'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishments',
            name='picture',
            field=models.ImageField(upload_to='establishments', verbose_name='Изображение'),
        ),
    ]
