# Generated by Django 5.0.1 on 2024-05-13 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeexplorer_app', '0007_alter_establishments_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='establishments',
            name='pets',
        ),
        migrations.AddField(
            model_name='establishments',
            name='big_pets',
            field=models.BooleanField(default=0, verbose_name='Наличие возможности посетить с большой собакой питомцем'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='establishments',
            name='small_pets',
            field=models.BooleanField(default=0, verbose_name='Наличие возможности посетить с маленькой собакой'),
            preserve_default=False,
        ),
    ]
