# Generated by Django 5.0.1 on 2024-05-13 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeexplorer_app', '0008_remove_establishments_pets_establishments_big_pets_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishments',
            name='big_pets',
            field=models.BooleanField(verbose_name='Наличие возможности посетить с большой собакой'),
        ),
    ]
