# Generated by Django 5.0.1 on 2024-05-16 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeexplorer_app', '0009_alter_establishments_big_pets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishments',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Описание'),
        ),
    ]
