# Generated by Django 5.0.1 on 2024-05-16 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeexplorer_app', '0010_alter_establishments_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishments',
            name='picture',
            field=models.ImageField(default='establishments/default.jpg', upload_to='establishments', verbose_name='Изображение'),
        ),
    ]
