# Generated by Django 5.0.1 on 2024-05-23 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeexplorer_app', '0011_alter_establishments_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishments',
            name='specialty_coffee',
            field=models.BooleanField(default=1, verbose_name='Наличие specialty кофе'),
            preserve_default=False,
        ),
    ]
